/* This class has language variables in it, used for Türkiye edition of Psych Extended Online */

class Language {
	public static var turkishTexts:Map<String, String> = [
		// Ratingler
		"You Suck!"	 => "Çok Kötü!",
		"Shit"		  => "Berbat!",
		"Bad"		   => "Kötü",
		"Bruh"		  => "Eh işte...",
		"Meh"		   => "İdare eder",
		"Nice"		  => "İyi",
		"Good"		  => "Güzel",
		"Great"		 => "Harika",
		"Sick!"		 => "Müthiş!",
		"Perfect!!"	 => "Mükemmel!!",
		
		// Değişkenler
		"multiplicative" => "çarpıcı",
		"WEEK SCORE:" => "HAFTA SKORU:",
		
		// Online Elemanları
		"In-Game"	 => "Oyunda",
		"Playing a online game!"	 => "Online Maçta",
		"Playing a online private game!"	 => "Özel Online Maçta",
		"Story Mode: "	 => "Hikaye Modu: ",
		"'s Replay"	 => "'nin Replay'i",
		"Paused - "	 => "Durduruldu - ",
		"TOUCH YOUR SCREEN TO START"	 => "BAŞLATMAK IÇIN EKRANA TIKLAYIN",
		"PRESS ACCEPT TO START"	 => "BAŞLATMAK IÇIN ACCEPT'A BASIN",
		
		"All Time" => "Her Zaman",

		// Pause Menüsü Elemanları
		"Resume"                => "Devam Et",
		"Restart Song"          => "Yeniden Başlat",
		"Change Difficulty"     => "Zorluğu Değiştir",
		"Leave Charting Mode"   => "Charting Modundan Çık",
		"Skip Time"             => "Zaman Atla",
		"End Song"              => "Şarkıyı Bitir",
		"Toggle Practice Mode"  => "Pratik Modunu Aç/Kapat",
		"Toggle Botplay"        => "Bot Oynanışını Aç/Kapat",
		"Options"               => "Ayarlar",
		"Exit to menu"          => "Menüye Dön",
		"Exit to lobby"         => "Lobiye Dön",
		"Post a Comment Now"    => "Yorum Yaz",
		"Debug Tools"           => "Hata Ayıklama Araçları",
		"Save Replay"           => "Tekrarı Kaydet",
		"Report Replay"         => "Tekrarı Raporla",
		"Back"                  => "Geri",

		// Debug / Gelişmiş Araçlar
		"Playback Rate"         => "Şarkı Hızı",
		"Run Script"            => "Script Çalıştır",
		"Swap Sides"            => "Tarafları Değiştir",
		"Chart Editor"          => "Chart Düzenleyici",
		"Character Editor"      => "Karakter Düzenleyici",
		"Position Debug"        => "Pozisyon Hata Ayıklama",
		"Swing Mode"            => "Sallanma Modu",
		"Charting Mode"         => "Charting Modu",
		"Stage 3D Debug"        => "3D Sahne Hata Ayıklama",

		// Diğer Ekran Yazıları (Pause Menüsü içindeki küçük metinler)
		"PRACTICE MODE"         => "PRATİK MODU",
		"CHARTING MODE"         => "CHARTING MODU",
		"Retry No. "            => "Ölüm Sayısı: ",
		
		// Gameplay Ayarları
		"Mania"                     => "Tuş Sayısı",
		"Scroll Type"               => "Ok Hızı Türü",
		"Scroll Speed"              => "Ok Hızı",
		"Scroll Speed By Mania"     => "Tuş Sayısına Göre Ok Hızı",
		"HP Gain Multiplier"        => "Can Kazanma Çarpanı",
		"HP Loss Multiplier"        => "Can Kaybetme Çarpanı",
		"Botplay"                   => "Bot Oynanışı",
		"Instakill on Miss"         => "Iskada Ölüm",
		"Practice Mode"             => "Pratik Modu",
		"Play as Opponent"          => "Rakip Olarak Oyna",
		"No Hurt Notes"             => "Hasar Veren Notaları Sil",
	
		//Reset Score SubState
		"Reset the score of"             => "Bu Şarkının Skorunu Sıfırlamak Istiyormusunuz?:",
		"Yes"		=> "Evet",
		"No"		=> "Hayır",
		
		// FreeplayState
		"Freeplay" => "Serbest Oyun",
		"Choosing a Song" => "Şarkı Seçiyor",
		"SEARCH: '" => "ARA: '",
		"Missing file: " => "Eksik dosya: ",
		"Load Replay File" => "Tekrar Dosyası Yükle",
		"Default" => "Varsayılan",
		"All" => "Tümü",
		"Favorites" => "Favoriler",
		"Hidden" => "Gizli",
		" MIX" => " KARIŞIMI",
		"SCORE" => "SKOR",
		"ACCURACY" => "DOĞRULUK",
		"RANK" => "RÜTBE",
		"RANKS" => "RÜTBELER",
		
		"PERSONAL BEST" => "EN İYİ SKOR",
		"PROTECT YO NUTS BOYFRIEND"       => "SOMUNLARINI KORU BOYFRIEND",
		"DON'T STOP BOYFRIEND"            => "DURMA BOYFRIEND",
		"FUNK 'EM UP BOYFRIEND"           => "GÖSTER GÜNÜNÜ BOYFRIEND",
		"GO FOR A 100% BOYFRIEND"         => "HEDEF %100 BOYFRIEND",
		"GO WITH THE RHYTHM BOYFRIEND"    => "RİTME AYAK UYDUR BOYFRIEND",
		"STAY FUNKY BOYFRIEND"            => "YATAĞINDAYIM BOYFRIEND",
		"GET LAID BOYFRIEND"              => "ŞANSINI DENE BOYFRIEND",
		"DON'T KNOCK UP BOYFRIEND"        => "ÇUVALLAMA BOYFRIEND",
		"BEHIND YOU BOYFRIEND"            => "ARKANDAYIM BOYFRIEND",
		"DRINK PISS BOYFRIEND"            => "GİT Bİ' ÇAY İÇ BOYFRIEND",
		"COME TO BRAZIL BOYFRIEND"        => "BAĞCILARA GEL BOYFRIEND",
		"FUNK THEIR BRAINS OUT BOYFRIEND" => "SAMETİ SİK BOYFRIEND",
		
		// Visuals & UI Settings
		"Language:" => "Dil:",
		"Select your language. \n(This is temporary option, will have own state later)" => "Dilinizi seçin. \n(Bu geçici bir seçenektir, ileride kendi state'i olacaktır)",
		"Adjust Positions" => "Pozisyonları Ayarla",
		"Customize the offsets for combo and rating sprites here!" => "Kombinasyon ve rating sprite'larının ofsetlerini buradan özelleştirebilirsiniz!",
		"Select your language." => "Dilini Seç.",
		"Disable RGB" => "RGB'yi Kapat",
		"Set the colors for your notes!" => "Notlarınızın renklerini ayarlayın!",
		"If checked, notes will use the HSV coloring method." => "İşaretlenirse, notalar HSV renk yöntemini kullanır\n(bu özellik online'da bozukdur).",
		"Note Skins:" => "Nota Görünümleri:",
		"Select your prefered Note skin." => "Tercih ettiğin nota görünümünü seç.",
		"Note Splashes:" => "Nota Sıçramaları:",
		"Select your prefered Note Splash variation or turn it off." => "Tercih ettiğin nota sıçrama varyasyonunu seç veya kapat.",
		"Note Splash Opacity" => "Nota Sıçrama Opaklığı",
		"How much transparent should the Note Splashes be.\n0% disables it." => "Nota sıçramalarının ne kadar şeffaf olacağını belirler.\n%0 devre dışı bırakır.",
		"Note Hold Splash Opacity" => "Uzun Nota Sıçrama Opaklığı",
		"How much transparent should the Note Hold Splash be.\n0% disables it." => "Uzun nota (sustain) sıçramalarının ne kadar şeffaf olacağını belirler.\n%0 devre dışı bırakır.",
		"Trail Note Opacity" => "Nota izinin Opaklığı",
		"How much transparent should the Note Trail be." => "Nota izlerinin (kuyruklarının) ne kadar şeffaf olacağını belirler.",
		"Hide HUD" => "Arayüzü Gizle",
		"If checked, hides most HUD elements." => "İşaretlenirse, çoğu arayüz öğesini gizler.",
		"Time Bar:" => "Zaman Çubuğu:",
		"What should the Time Bar display?" => "Zaman çubuğu neyi göstermeli?",
		"Flashing Lights" => "Yanıp Sönen Işıklar",
		"Uncheck this if you're sensitive to flashing lights!" => "Eğer yanıp sönen ışıklara karşı hassasiyetiniz varsa bunu kapatın!",
		"Camera Zooms" => "Kamera Yakınlaştırmaları",
		"If unchecked, the camera won't zoom in on a beat hit." => "İşaretlenmezse, kamera vuruşlarda (beat hit) yakınlaştırma yapmaz.",
		"Score Text Zoom on Hit" => "Tıklamada Puan Yakınlaştırma",
		"If unchecked, disables the Score text zooming\neverytime you hit a note." => "İşaretlenmezse, her nota vurduğunuzda puan\nmetninin yakınlaşmasını devre dışı bırakır.",
		"Health Bar Opacity" => "Can Çubuğu Opaklığı",
		"How much transparent should the health bar and icons be." => "Can çubuğunun ve ikonların ne kadar şeffaf olacağını belirler.",
		"FPS Counter" => "FPS Sayacı",
		"If unchecked, hides FPS Counter." => "İşaretlenmezse, FPS sayacını gizler.",
		"Disable Online Shaders" => "Çevrimiçi Shaderları Kapat",
		"If checked, disables shaders that being used on online menus." => "İşaretlenirse, çevrimiçi menülerde kullanılan shaderları devre dışı bırakır.",
		"Pause Screen Song:" => "Duraklatma Ekranı Müziği:",
		"What song do you prefer for the Pause Screen?" => "Duraklatma ekranı için hangi müziği tercih edersiniz?",
		"Check for Updates" => "Güncellemeleri Kontrol Et",
		"On Release builds, turn this on to check for updates when you start the game." => "Tam sürüm yapılarında, oyunu başlattığınızda güncellemeleri kontrol etmek için bunu açın.",
		"Discord Rich Presence" => "Discord Zengin Varlık",
		"Uncheck this to prevent accidental leaks, it will hide the Application from your \"Playing\" box on Discord" => "Yanlışlıkla sızıntı yapmamak için bunu kapatın; Discord'daki \"Oynuyor\" kutusunda uygulamayı gizleyecektir.",
		"Debug Mode" => "Hata Ayıklama Modu",
		"If checked, enables debug warnings etc." => "İşaretlenirse, hata ayıklama uyarılarını vb. etkinleştirir.",
		"Show Note Timing" => "Nota Zamanlamasını Göster",
		"If checked, a timing of the hitted note will be shown on the screen (in miliseconds)" => "İşaretlenirse, vurulan notanın zamanlaması ekranda gösterilir (milisaniye cinsinden).",
		"Disable Automatic Downloads" => "Otomatik indirmeleri Kapat",
		"Disables automatic downloads of Mods and Skins from the opponent" => "Rakipten gelen modların ve görünümlerin otomatik indirilmesini devre dışı bırakır.",
		"Disable Song Comments" => "Şarkı Yorumlarını Kapat",
		"Disables song comments on the replay viewer and (if visible, while playing)" => "Tekrar izleyicideki ve (görünürse oyun sırasındaki) şarkı yorumlarını devre dışı bırakır.",
		"Song Comments Opacity" => "Şarkı Yorumu Opaklığı",
		"How visible should the song comments be while you're playing a song" => "Şarkı oynarken yorumların ne kadar görünür olacağını belirler.",
		"Show Funkin Points Counter" => "Funkin Points Sayacını Göster",
		"If checked, the current FP count will be shown in the score text, can be toggled in-game with F7" => "İşaretlenirse, mevcut FP sayısı puan metninde gösterilir, oyun içinde F7 ile değiştirilebilir.",
		"FP V5 Preview" => "FP V5 Önizlemesi",
		"If enabled, new FP algorithm will be shown in the Counter" => "Etkinleştirilirse, sayaçta yeni FP algoritması gösterilir.",
		"Group Songs:" => "Şarkıları Grupla:",
		"How should songs on Freeplay menu be group by?" => "Serbest Oynanış menüsündeki şarkılar neye göre gruplandırılmalı?",
		"Rating Color" => "Derece Rengi",
		"If checked, the Rating text will be colored depending on your current... well... Rating, same with Combo." => "İşaretlenirse, Derece metni ve Kombo mevcut derecenize göre renklendirilir.",
		"Favorite Tracks Menu Theme" => "Favori Parçalar Menü Teması",
		"If checked, the game will be picking your random favorite song as the main menu theme!" => "İşaretlenirse, oyun ana menü teması olarak rastgele bir favori şarkınızı seçecektir!",
		"Disable Combo Rating" => "Kombo Derecesini Kapat",
		"If checked, the combo rating sprite will no longer show up." => "İşaretlenirse, kombo derecesi görseli artık görünmez.",
		"Disable Combo Counter" => "Kombo Sayacını Kapat",
		"If checked, the combo counter sprite will no longer show up." => "İşaretlenirse, kombo sayacı görseli artık görünmez.",
		"Nameplate Fade Time" => "Isim Plakası Kaybolma Süresi",
		"After how many seconds should player nameplates be hidden?\nSet to 0 to instantly hide them.\nSet to -1 to never hide them." => "Oyuncu isim plakaları kaç saniye sonra gizlensin?\nAnında gizlemek için 0, hiç gizlememek için -1 yapın.",
		"Camera Shakes" => "Kamera Sallanmaları",
		"If unchecked, camera will be allowed to shake." => "İşaretlenmezse, kamera'nın sallanmasına izin verilir.",
		"Camera Tilt" => "Kamera Eğimi",
		"If unchecked, camera will be allowed to tilt." => "İşaretlenmezse, kamera'nın eğilmesine izin verilir.",
		"Camera Movement" => "Kamera Hareketi",
		"If unchecked, camera will move instead of being locked still on girlfriend." => "İşaretlenmezse, kamera kız arkadaşın üzerinde sabit kalmak yerine hareket edecektir.",
		
		// Graphics Settings (Birebir Map Eşleşmesi)
		"Performance" => "Performans",
		"Performance Settings Menu" => "Performans Ayarları Menüsü",
		"Low Quality" => "Düşük Kalite",
		"If checked, disables some background details,\ndecreases loading times and improves performance." => "İşaretlenirse, bazı arkaplan detaylarını kapatır,\nyükleme sürelerini azaltır ve performansı artırır.",
		"Anti-Aliasing" => "Kenar Yumuşatma",
		"If unchecked, disables anti-aliasing, increases performance\nat the cost of sharper visuals." => "İşaretlenmezse, kenar yumuşatmayı kapatır, performansı artırır\nancak görseller daha keskin olur.",
		"Shaders" => "Gölgelendiriciler",
		"If unchecked, disables shaders.\nIt's used for some visual effects, and also CPU intensive for weaker devices." => "İşaretlenmezse, gölgelendiricileri kapatır.\nBazı görsel efektler için kullanılır ve zayıf cihazlar için CPU yoğundur.",
		"Framerate" => "Kare Hızı",
		"Pretty self explanatory, isn't it?" => "Oldukça açıklayıcı, değil mi?",
		"Max FPS" => "Maksimum FPS",
		"If checked, the FPS limit will be set to 1000.\nThis setting makes the input timing more accurate, but in cost of minor graphical issues." => "İşaretlenirse, FPS limiti 1000'e ayarlanır.\nBu ayar giriş zamanlamasını daha doğru yapar, ancak küçük grafik sorunlarına neden olabilir.",
		"Disable Text Item Icons" => "Metin Ögesi İkonlarını Kapat",
		"If checked, menu text item icons will not be loaded, greatly decreases loading times." => "İşaretlenirse, menü metin ögesi ikonları yüklenmez, yükleme sürelerini büyük ölçüde azaltır.",
		"Disable Text Item Alphabet" => "Metin Ögesi Alfabesini Kapat",
		"If checked, various menu elements will be rendered using the pixel font." => "İşaretlenirse, çeşitli menü öğeleri piksel yazı tipi kullanılarak işlenir.",
		"Combo Stacking" => "Kombo Yığılması",
		"If unchecked, Ratings and Combo won't stack, saving on System Memory a little and making them easier to read" => "İşaretlenmezse, Derecelendirmeler ve Kombo yığılmaz, sistem belleğinden biraz tasarruf sağlar ve okunmalarını kolaylaştırır",
		
		// Gameplay Settings
		"Gameplay Settings Menu" => "Oynanış Ayarları Menüsü",
		"Old Camera System" => "Eski Kamera Sistemi",
		"If checked, game uses old camera system instead of new one.\n(If you have a any camera issue, enable or disable this)" => "İşaretlenirse, oyun yeni sistem yerine eski kamera sistemini kullanır.\n(Herhangi bir kamera sorununuz varsa, bunu etkinleştirin veya devre dışı bırakın)",
		"Disable Camera Rotate" => "Kamera Dönüşünü Kapat",
		"If checked, camera angle works like in Codename Engine,\nThis is useful for some CNE mods like Cyber Sensation" => "İşaretlenirse, kamera açısı Codename Engine'deki gibi çalışır,\nBu, Cyber Sensation gibi bazı CNE modları için kullanışlıdır",
		"Downscroll" => "Aşağı Kaydırma",
		"If checked, notes go Down instead of Up, simple enough." => "İşaretlenirse, notalar Yukarı yerine Aşağı gider, oldukça basit.",
		"Middlescroll" => "Orta Kaydırma",
		"If checked, your notes get centered." => "İşaretlenirse, notalarınız ortaya hizalanır.",
		"Opponent Notes" => "Rakip Notaları",
		"If unchecked, opponent notes get hidden." => "İşaretlenmezse, rakip notaları gizlenir.",
		"Ghost Tapping" => "Hayalet Dokunuş",
		"If checked, you won't get misses from pressing keys\nwhile there are no notes able to be hit." => "İşaretlenirse, vurulabilecek nota olmadığında tuşlara basmaktan ıska almazsınız.",
		"Auto Pause" => "Otomatik Duraklat",
		"If checked, the game automatically pauses if the screen isn't on focus." => "İşaretlenirse, ekran odakta değilse oyun otomatik olarak duraklatılır.",
		"Disable Reset Button" => "Sıfırlama Tuşunu Kapat",
		"If checked, pressing Reset won't do anything." => "İşaretlenirse, Sıfırlama tuşuna basmak hiçbir şey yapmaz.",
		"Hitsound Volume" => "Vuruş Sesi Seviyesi",
		'Funny notes does \"Tick!\" when you hit them."' => "Komik notalar vurduğunuzda \"Tık!\" sesi çıkarır.",
		"Rating Offset" => "Puanlama Dengesi",
		"Changes how late/early you have to hit for a \"Sick!\"\nHigher values mean you have to hit later." => "\"Müthiş!\" için ne kadar geç/erken vurmanız gerektiğini değiştirir.\nDaha yüksek değerler daha geç vurmanız gerektiği anlamına gelir.",
		"Safe Frames" => "Güvenli Kareler",
		"Changes how many frames you have for\nhitting a note earlier or late." => "Bir notayı erken veya geç vurmak için kaç kareniz olduğunu değiştirir.",
		"Disable Note Modchart" => "Nota Modchart'ı Kapat",
		"If checked, strum notes will no longer move or change their opacity to invisible." => "İşaretlenirse, strum notaları artık hareket etmez veya opaklığını görünmez olarak değiştirmez.",
		"Disable Recording Replays" => "Tekrar Kaydını Kapat",
		"If checked, the game will no longer record your gameplay, this will cause your scores to not be submitted to the leaderboard!" => "İşaretlenirse, oyun artık oynanışınızı kaydetmez, bu skorlarınızın liderlik tablosuna gönderilmemesine neden olur!",
		"Disable Leaderboard Submiting" => "Lider Listesi Gönderimini Kapat",
		"If checked, the game will no longer submit your replays to the leaderboard\nCan be toggled in-game with F2" => "İşaretlenirse, oyun artık tekrarlarınızı liderlik tablosuna göndermez\nOyun içinde F2 ile değiştirilebilir",
		"Disable Lag Detection" => "Gecikme Algılamasını Kapat",
		"If checked, the game will no longer rewind 3 seconds when a lag is detected" => "İşaretlenirse, bir gecikme algılandığında oyun artık 3 saniye geri sarmaz",
		"Modchart Skin Changes" => "Modchart Skin Değişiklikleri",
		"If enabled, the song events will change the character of your active skin" => "Etkinleştirilirse, şarkı olayları aktif skin'inizin karakterini değiştirir",
		"Note Underlay Opacity" => "Nota Altlık Opaklığı",
		"If higher than 0%, an underlay will be displayed behind player notes." => "%0'dan yüksekse, oyuncu notalarının arkasında bir altlık görüntülenir.",
		"Note Underlay Type:" => "Nota Altlık Türü:",
		"How should the game render note underlays." => "Oyun nota altlıklarını nasıl render etmeli.",
		"If checked, camera updates directly instead of waiting to next section" => "Bu seçenek işaretlendiğinde, kamera beat'i beklemek yerine doğrudan güncellenir",
		"All-In-One" => "Hepsi Bir Arada",
		"By Note" => "Notaya Göre",
		
		// Freeplay Menu metinleri
		" / BACK to return to Songs" => "Şarkılara dönmek için BACK tuşuna basın",
		"ACCEPT to enter the Song / Use your Arrow Keys to change the Difficulty" => "KABUL ET şarkıyı açmak için / Ok tuşlarını kullanarak Zorluk Değiştirin",
		"ACCEPT to select the Song / %{1}% to listen to the Song / RESET to " => "şarkıyı seçmek için KABUL ET / %{1}% ile şarkıyı dinleyin / RESET ile şarkıyı",
		"show" => "göster",	
		"hide" => "gizle",
		" the Song" => "",
		" / TAB to select your character!" => " / TAB ile karakterinizi seçin!",
		"ACCEPT to open Gameplay Modifers Menu" => "KABUL ETME TUŞU ile Oynanış Ayarları Menüsünü açın",
		"ACCEPT to load a Replay data file" => "KABUL ET ile Tekrar dosyasını yükleyin",
		"ACCEPT to reset Score and Accuracy of this Song" => "KABUL ETME TUŞU ile bu Şarkının Skorunu ve Doğruluğunu sıfırlayın",
		"LEFT or RIGHT to Flip Pages / ACCEPT to view Player's replay of this song" => "SOL veya SAĞ ile Sayfa Çevir / KABUL ET ile oyuncunun tekrarını izleyin",
		"BACK to return to Songs" => "GERİ ile Şarkılara dön",
		"ERROR WHILE LOADING CHART" => "CHART YÜKLENIRKEN HATA",
		"OUTDATED REPLAY OR INVALID FOR THIS SONG" => "ESKİ REPLAY VEYA BU ŞARKI İÇİN GEÇERSİZ",
		"Loading..." => "Yükleniyor...",
		"Failed to fetch!" => "Yüklenemedi!",
		"Failed to load!" => "Yüklenemedi!",
		"ACCEPT to select a random song / %{1}% to select without loading / %{2}% to select song group" => "KABUL ET rastgele şarkı seçmek için / %{1}% yüklemeden seçmek için / %{2}% şarkı grubu seçmek için",
		"PRESS F TO SEARCH" => "ARAMAK İÇİN F'YE BASIN",
		"SEARCH" => "ARA",
		
		// Controls Settings
		"Controls Menu" => "Kontroller Menüsü",
		"Reset to Default Keys" => "Varsayılan Tuşlara Sıfırla",
		"Switch Input Device" => "Giriş Cihazını Değiştir",
		"Switch Note Mania" => "Tuş Sayısını Değiştir",
		"NOTES" => "NOTALAR",
		"Note" => "Nota",
		"Left" => "Sol",
		"Down" => "Aşağı",
		"Up" => "Yukarı",
		"Right" => "Sağ",
		"Note Left" => "Nota Sol",
		"Note Down" => "Nota Aşağı",
		"Note Up" => "Nota Yukarı",
		"Note Right" => "Nota Sağ",
		"UI" => "ARAYÜZ",
		"UI Left" => "Arayüz Sol",
		"UI Down" => "Arayüz Aşağı",
		"UI Up" => "Arayüz Yukarı",
		"UI Right" => "Arayüz Sağ",
		"Taunt" => "Alay",
		"Reset" => "Sıfırla",
		"Accept" => "Kabul Et",
		"Pause" => "Durdur",
		"Sidebar" => "Kenar Çubuğu",
		"Favor" => "Favori",
		"VOLUME" => "SES",
		"Mute" => "Sessiz",
		"Volume Mute" => "Sesi Kapat",
		"Volume Up" => "Sesi Aç",
		"Volume Down" => "Sesi Kıs",
		"DEBUG" => "HATA AYIKLAMA",
		"Key 1" => "Tuş 1",
		"Key 2" => "Tuş 2",
		"Debug Key #1" => "Hata Ayıklama Tuşu #1",
		"Debug Key #2" => "Hata Ayıklama Tuşu #2",
		"Rebinding" => "Yeniden Ayarlanıyor",
		"Hold ESC to Cancel" => "İptal etmek için ESC'ye basılı tutun",
		"Hold Backspace to Delete" => "Silmek için Backspace'e basılı tutun",
		
		// Menü ve Leaderboard Başlıkları
		"GAMEPLAY MODIFIERS"      => "OYNANIŞ MODIFiKASYONLARI",
		"MODIFIERS UNAVAILABLE HERE" => "MODiFiKASYONLAR BURADA KULLANILAMAZ",
		"LOAD REPLAY"             => "TEKRARI YÜKLE",
		"REPLAYS UNAVAILABLE"     => "TEKRARLAR KULLANILAMAZ",
		"RESET SCORE"             => "SKORU SIFIRLA",
		"< ALL TIME >"            => "< TÜM ZAMANLAR >",
		"< WEEKLY >"            => "< HAFTALIK >",
		"< All Time >"            => "< Tüm Zamanlar >",
		"< Weekly >"            => "< Haftalık >",
		"PLAYER"            => "OYUNCU",
		"LOADING"                 => "YÜKLENİYOR",
		"LOADING..."                 => "YÜKLENİYOR...",
		"FlashingState.warnText"  => "Hey, dikkat et!\n
			Bu Oyun, bazı yanıp sönen ışıklar içeriyor!\n
			Flaşları kapatmak veya Ayarlar'a gitmek için %{1}% tuşuna basın.\n
			Bu mesajı görmezden gelmek için %{2}% tuşuna basın.\n
			Uyarıldınız!",

		// Zorluklar
		"NIGHTMARE" => "KABUS",
		"HARD" => "ZOR",
		"EASY" => "KOLAY",
		"VERY HARD" => "ÇOK ZOR",
		"CLASSIC" => "KLASİK",
		"HELL" => "CEHENNEM",
		"INSANE" => "ÇILGIN",
		"DEATH" => "ÖLÜM",
		"PORNO" => "NE VAR YARRAM -ARKOSELABS",

		// Achievements
		"Reset Achievement:" => "Basarımı Sıfırla:",
		"Freaky on a Friday Night" => "Cuma Gecesi Eğlencesi",
		"Play on a Friday... Night." => "Bir Cuma... Gecesinde oyna.",
		"She Calls Me Daddy Too" => "O da Bana Babacık Diyor",
		"Beat Week 1 on Hard with no Misses." => "1. Haftayı Hard zorlukta hiç kaçırmadan bitir.",
		"No More Tricks" => "Numara Yapmak Yok",
		"Beat Week 2 on Hard with no Misses." => "2. Haftayı Hard zorlukta hiç kaçırmadan bitir.",
		"Call Me The Hitman" => "Bana Tetikçi De",
		"Beat Week 3 on Hard with no Misses." => "3. Haftayı Hard zorlukta hiç kaçırmadan bitir.",
		"Lady Killer" => "Kadın Avcısı",
		"Beat Week 4 on Hard with no Misses." => "4. Haftayı Hard zorlukta hiç kaçırmadan bitir.",
		"Missless Christmas" => "Hatasız Noel",
		"Beat Week 5 on Hard with no Misses." => "5. Haftayı Hard zorlukta hiç kaçırmadan bitir.",
		"Highscore!!" => "Yüksek Skor!!",
		"Beat Week 6 on Hard with no Misses." => "6. Haftayı Hard zorlukta hiç kaçırmadan bitir.",
		"God Effing Damn It!" => "Hadi Oradan Be!",
		"Beat Week 7 on Hard with no Misses." => "7. Haftayı Hard zorlukta hiç kaçırmadan bitir.",
		"What a Funkin' Disaster!" => "Tam Bir Funkin' Felaketi!",
		"Complete a Song with a rating lower than 20%." => "Bir şarkıyı %20'den daha düşük bir dereceyle tamamla.",
		"Perfectionist" => "Mükemmeliyetçi",
		"Complete a Song with a rating of 100%." => "Bir şarkıyı %100 dereceyle tamamla.",
		"Roadkill Enthusiast" => "Ezilme Meraklısı",
		"Watch the Henchmen die 50 times." => "Yardımcıların ölmesini 50 kez izle.",
		"Oversinging Much...?" => "Biraz Fazla mı Söylüyorsun...?",
		"Sing for 10 seconds without going back to Idle." => "Boşta durma (Idle) animasyonuna dönmeden 10 saniye boyunca şarkı söyle.",
		"Hyperactive" => "Hiperaktif",
		"Finish a Song without going back to Idle." => "Boşta durma (Idle) animasyonuna hiç dönmeden bir şarkıyı bitir.",
		"Just the Two of Us" => "Sadece İkimiz",
		"Finish a Song pressing only two keys." => "Sadece iki tuşa basarak bir şarkıyı bitir.",
		"Toaster Gamer" => "Tost Makinesi Oyuncusu",
		"Have you tried to run the game on a toaster?" => "Oyunu bir tost makinesinde çalıştırmayı denedin mi?",
		"Debugger" => "Hata Ayıklayıcı",
		"Beat the \"Test\" Stage from the Chart Editor." => "Chart Editor'deki \"Test\" aşamasını bitir.",
		"It's over 1000!" => "1000'den Fazla!",
		"Completed a Song with combo higher than 1000." => "Bir şarkıyı 1000'den yüksek kombo ile tamamla.",

		//Ayarlar
		"Note Colors" => "Nota Renkleri",
		"Controls" => "Kontroller",
		"Adjust Delay and Combo" => "Gecikme ve Kombo",
		"Graphics" => "Grafikler",
		"Visuals" => "Görseller",
		"Gameplay" => "Oynanış",
		"Game" => "Oyun",
		"Preferences" => "Tercihler",
		"Adjust Audio Delay" => "Ses Gecikmesini Ayarla",
		"Mobile" => "Mobil Ayarlar",
		"Notes" => "Notalar",
		"Combo & Rating" => "Kombo & Rating",
		"User Interface" => "Kullanıcı Arayüzü",
		"Accessibility" => "Erişebilirlilik",

		//Mobil Ayarlar
		"MobilePad Opacity" => "MobilePad Opaklığı",
		"Selects the opacity for the mobile buttons (careful not to put it at 0 and lose track of your buttons)." => "Mobil düğmelerin opaklığını seçer (0 olarak ayarlayıp düğmelerinizi kaybetmeyin).",
		"Extra Controls" => "Ekstra Kontroller",
		"Allow Extra Controls" => "Kaç tane ektra kontrol ekleneyeceğini seçiniz",
		"Hitbox Mode" => "Hitbox Modu",
		"Choose your Hitbox Style!" => "Hitbox stilini seç!",
		"Hitbox Design" => "Hitbox Şekli/Dizaynı",
		"Choose how your hitbox should look like." => "Hitbox nasıl görünmeli?",
		// Uyarılar (Alerts)
		
		
		// ModsMenuState
		"ON" => "AÇIK",
		"OFF" => "KAPALI",
		"TOP" => "EN ÜSTE",
		"DISABLE ALL" => "TÜMÜNÜ DEVRE DIŞI BIRAK",
		"ENABLE ALL" => "TÜMÜNÜ ETKİNLEŞTİR",
		"VERIFY" => "DOĞRULA",
		"DEL" => "SİL",
		"GLOBAL" => "GLOBAL",
		"LOCAL" => "YEREL",
		"SETTINGS" => "AYARLAR",
		"NO MODS INSTALLED\nPRESS BACK TO EXIT AND INSTALL A MOD" => "YÜKLÜ MOD YOK\nÇIKMAK VE MOD YÜKLEMEK İÇİN GERİ BASIN",
		" (This Mod will restart the game!)" => " (Bu Mod oyunu yeniden başlatacak!)",
		"No description provided." => "Açıklama sağlanmadı.",
		"No mod URL provided!" => "Mod URL'si sağlanmadı!",
		"Other players will not be able to download this mod!\nPlease set it in the Setup Mods option!" => "Diğer oyuncular bu modu indiremeyecek!\nLütfen bunu Mod Kurulumu seçeneğinden ayarlayın!",
		"\nBITCH." => "\nAMK.",
		
		"In the Menus" => "Menülerde",
		"Mods" => "Modlar",
		
		// OnlineState.hx
		"JOIN" => "ODAYA KATIL",
		"HOST" => "ODA AÇ",
		"FIND" => "ODA BUL",
		"LEADERBOARD" => "LiDERLiK TABLOSU",
		"MOD DOWNLOADER" => "MOD YÜKLEYİCİ",
		"OPTIONS" => "AYARLAR",
		// OnlineState - Yeni Eklenecekler
		"JOIN CODE: " => "ODA KODU: ",
		"Fetching..." => "Bağlanılıyor...",
		"NETWORK OFFLINE" => "AĞ ÇEVRİMDIŞI",
		"Players Online: " => "Çevrimiçi Oyuncular: ",
		"Available Rooms: " => "Çevrimiçi Odalar: ",

		// OnlineState - Uyarı Metinleri
		"WARNING" => "UYARI",
		" of your mods do not have a valid URL set!" => " modlarınızın geçerli bir URL'si ayarlanmamış!",
		
		"Join Psych Online Discord Server!" => "Psych Online Discord Sunucusuna Katıl!",
		"Documentation, FAQ and the Source Code!" => "Dökümanlar, SSS ve Kaynak Kodu!",
		"Follow the official Psych Online Bluesky account!" => "Resmi Psych Online Bluesky hesabını takip et!",
		"Follow the official Psych Online Twitter account!" => "Resmi Psych Online Twitter hesabını takip et!",
		"Offline." => "Çevrimdışı.",

		"Join a room using a room code" => "Oda kodu kullanarak bir odaya katıl",
		"Creates a room" => "Bir oda oluşturur",
		"Opens a list of all available public rooms" => "Tüm mevcut genel odaların listesini açar",
		"Psych Online options, configure stuff here!" => "Psych Online ayarları, buradan yapılandır!",
		"The Funkin Points Leaderboard!" => "Funkin Puanları Liderlik Tablosu!",
		"Download mods from Gamebanana here!" => "Gamebanana'dan modları buradan indir!",

		"Online Menu" => "Online Menüsü",
		
		// GameClient
		"Failed to connect!" => "Bağlanılamadı!",
		"JOIN ERROR: " => "KATILMA HATASI: ",
		"Room error!" => "Oda hatası!",
		"room.onError: " => "oda.Hata: ",
		"Reconnecting..." => "Yeniden bağlanıyor...",
		"Couldn't reconnect!" => "Yeniden bağlanılamadı!",
		"RECONNECT ERROR: " => "YENİDEN BAĞLANMA HATASI: ",
		"Reconnected!" => "Yeniden bağlandı!",
		"Critically failed to reconnect!" => "Yeniden bağlanma kritik şekilde başarısız oldu!",
		"Disconnected!" => "Bağlantı kesildi!",
		"Switching Rooms." => "Oda değiştiriliyor.",
		"Room Disposed?" => "Oda Kapatıldı mı?",
		"Left/Kicked from room: " => "Odadan ayrıldı/atıldı: ",
		"Left/Kicked from unknown room!" => "Bilinmeyen odadan ayrıldı/atıldı!",
		"Joined!" => "Katıldı!",
		"Leaving the Room, Reason: " => "Odadan Ayrılıyor, Sebep: ",
		"Reconnecting with Token: " => "Token ile yeniden bağlanıyor: ",
		
		// RoomState.hx
		"In the Lobby" => "Lobide",
		"Typing..." => "Yazıyor...",
		"Downloading (" => "İndiriliyor (",
		"Caught an exception!" => "Bir hata oluştu!",
		"You don't have the current stage!" => "Mevcut Arka Plana sahip değilsiniz!",
		"Song isn't selected!" => "Şarkı seçilmedi!",
		"You don't have the current song/mod!" => "Mevcut şarkıya/moda sahip değilsiniz!",
		"Only the host can do that!" => "Bunu sadece Oda Sahibi yapabilir!",
		"Room code copied!" => "Oda kodu kopyalandı!",
		"You already have this song installed!" => "Bu şarkı zaten yüklü!",
		"Mod couldn't be found!" => "Mod bulunamadı!",
		"Host didn't specify the URL of this mod" => "Oda Sahibi bu modun URL'sini belirtmedi",
		"Expected mod data to exist in this path: " => "Mod verilerinin bu yolda olması bekleniyor: ",
		"Room Code: ????" => "Oda Kodu: ????",
		"Room Code: \"" => "Oda Kodu: \"",
		"Selected Song: " => "Seçilen Şarkı: ",
		"(None)" => "(Yok)",
		" (Not found!)" => " (Bulunamadı!)",
		"No chosen mod." => "Seçili mod yok.",
		"No mod named: " => "İsim Belirtilmedi: ",
		" (Unknown; Host didn't specify mod's URL)" => " (Bilinmiyor; Oda Sahibi modun URL'sini belirtmedi)",
		" (Download/Verify it here!)" => " (Buradan İndir/Doğrula!)",
		"\n\n(Keybind: SHIFT)" => "\n\n(Tuş Ataması: SHIFT)",
		"\n\n(Keybind: TAB)" => "\n\n(Tuş Ataması: TAB)",
		"\n\nACCEPT - Reveals the code and\ncopies it to your clipboard.\n\nCTRL + C - Copies the code without\nrevealing it on the screen." => "\n\nKABUL ET - Kodu gösterir ve\npanonuza kopyalar.\n\nCTRL + C - Kodu ekranda göstermeden\nkopyalar.",
		"\n\nTOUCH - Reveals the code and\ncopies it to your clipboard." => "\n\nDOKUN - Kodu gösterir ve\npanonuza kopyalar.",
		"\n\nRIGHT CLICK - Open Mod Downloader" => "\n\nSAĞ TIKLAMA - Mod İndiriciyi Aç",
		"\n\nTOUCH - Open Mod Downloader" => "\n\nDOKUN - Mod İndiriciyi Aç",
		"\nPress UI keybinds\nor use your mouse\nto select an option!" => "\nArayüz tuşlarına basın\nveya farenizi kullanarak\nbir seçenek seçin!",
		"\nTouch UI keybinds\nto select an option!" => "\nArayüz tuşlarına dokunarak\nbir seçenek seçin!",
		" - SETTINGS - \nOpens server settings." => " - AYARLAR - \nSunucu ayarlarını açar.",
		" - CHAT - \nOpens chat." => " - SOHBET - \nSohbeti açar.",
		" - START GAME/READY - \nToggles your READY status.\n\nPlayers also need to have the\ncurrently selected mod installed.\n\n(Both sides can only\nhave up to 2 players)." => " - OYUNU BAŞLAT/HAZIR - \nHAZIR durumunuzu değiştirir.\n\nOyuncuların da seçili modu\nyüklü olması gerekir.\n\n(Her iki tarafta da en fazla\n2 oyuncu olabilir).",
		" - ROOM CODE - \nUnique code of this room." => " - ODA KODU - \nBu odanın benzersiz kodu.",
		" - SELECT SONG - \nSelects the song.\n\n(Players with host permissions\ncan only do that)" => " - ŞARKI SEÇ - \nŞarkıyı seçer.\n\n(Bunu sadece host yetkisine\nsahip oyuncular yapabilir)",
		" - MOD - \nDownloads the currently selected mod\nif it isn't installed.\n\nAfter you install it\npress this button again!" => " - MOD - \nSeçili modu yüklü değilse\nindirir.\n\nYükledikten sonra\nbu butona tekrar basın!",
		" - LOBBY - " => " - LOBİ - ",
		"DOWNLOAD SKIN" => "SKİNİ YÜKLE",
		"FP (" => "FP (",
		"Ping: " => "Gecikme: ",
		"ms" => "ms",
		"NOT " => "DEĞİL ",
		"NOT READY" => "HAZIR DEĞİL",
		"READY" => "HAZIR",
		"\n(Unloaded Skin)" => "\n(Yüklenmeyen Skin)",
		"> Please enter the animation you want to play!\nAvailable animations: " => "> Lütfen oynamak istediğiniz animasyonu girin!\nMevcut animasyonlar: ",
		"> Room Commands: /pa <anim>, /results, /restage" => "> Oda Komutları: /pa <anim>, /results, /restage",
		
		// OnlineOptionsState
		"Online Options" => "Online Ayarlar",
		"General" => "Genel",
		"Account" => "Hesap",
		"Nickname" => "Oyuncu İsmi",
		"Set your nickname here!" => "Oyun-içi İsminizi buradan ayarlayın!",
		"Skin" => "Skin",
		"Choose your skin here!" => "Skin'inizi buradan seçin!",
		"Setup Mods" => "Modları Ayarla",
		"Set the URL's of your mods here!" => "Modlarınızın URL'lerini buradan ayarlayın!",
		"Server Address" => "Sunucu Adresi",
		"The server that hosts Game Rooms.\nSet to empty if you want to use the default server.\n\nLocal Address: 'localhost'" => "Oyun Odalarını barındıran sunucu.\nVarsayılan sunucuyu kullanmak için boş bırakın.\n\nYerel Adres: 'localhost'",
		"\nOfficial Servers:" => "\nResmi Sunucular:",
		"Network Server Address" => "Ağ Sunucu Adresi",
		"The server for Network social features.\nSet to empty if you want to use the default server.\n\nDefault Server: " => "Ağ sosyal özellikleri için sunucu.\nVarsayılan sunucuyu kullanmak için boş bırakın.\n\nVarsayılan Sunucu: ",
		"Clear Trusted Domains" => "Güvenilen Alan Adlarını Temizle",
		"Clear the list of all trusted domains!" => "Tüm güvenilen alan adlarının listesini temizleyin!",
		"Cleared the trusted domains list!" => "Güvenilen alan adları listesi temizlendi!",
		"Enable SSL Verification" => "SSL Doğrulamasını Etkinleştir",
		"If checked, the game will check for valid SSL Certifications, which can lead to safer connections with downloads or rooms.\n(But It's not recommended because of Haxe's flawed sockets implementation.)" => "İşaretlenirse, oyun geçerli SSL Sertifikalarını kontrol eder, bu da indirmeler veya odalarla daha güvenli bağlantılara yol açabilir.\n(Ancak Haxe'nin hatalı soket uygulaması nedeniyle önerilmez.)",
		"Register to the Network" => "Ağa Kayıt Ol",
		"Join the Psych Online Network and submit your song replays\nto the leaderboards!" => "Psych Online Ağına katılın ve şarkı tekrarlarınızı\nliderlik tablolarına gönderin!",
		"Username" => "Kullanıcı Adı",
		"Email" => "E-posta",
		"No username set!" => "Kullanıcı adı ayarlanmadı!",
		"Successfully registered!" => "Başarıyla kayıt olundu!",
		"Login to the Network" => "Ağa Giriş Yap",
		"Input your email address here and wait for your One-Time Login Code!" => "E-posta adresinizi buraya girin ve Tek Kullanımlık Giriş Kodunuzu bekleyin!",
		"me@example.org" => "ben@ornek.com",
		"Successfully logged in!" => "Başarıyla giriş yapıldı!",
		"Network Chat Notifications" => "Ağ Sohbet Bildirimleri",
		"If checked, all messages from the Network Chat will be notified to you.\nCan be toggled with \"/notify\" Network command." => "İşaretlenirse, Ağ Sohbetinden gelen tüm mesajlar size bildirilir.\n\"/notify\" Ağ komutuyla açılıp kapatılabilir.",
		"Mute PM Notifications" => "Özel Mesaj Bildirimlerini Sessize Al",
		"If checked, PM notifications are muted.\nCan be toggled with \"/notify pm\" Network command." => "İşaretlenirse, özel mesaj bildirimleri sessize alınır.\n\"/notify pm\" Ağ komutuyla açılıp kapatılabilir.",
		"Mute Room Invites" => "Oda Davetlerini Sessize Al",
		"If checked, room invites are muted.\nCan be toggled with \"/notify roominvite\" Network command." => "İşaretlenirse, oda davetleri sessize alınır.\n\"/notify roominvite\" Ağ komutuyla açılıp kapatılabilir.",
		"Notify when Friend is Online" => "Arkadaş Çevrimiçi Olduğunda Bildir",
		"If checked, you'll receive a notification when your friend goes online.\nCan be toggled with \"/notify friend\" Network command." => "İşaretlenirse, arkadaşınız çevrimiçi olduğunda bildirim alırsınız.\n\"/notify friend\" Ağ komutuyla açılıp kapatılabilir.",
		"Leave a Global Message" => "Global Mesaj Bırak",
		"Leave a message for others to see in the Online Menu!\n(Please keep it English)" => "Başkalarının Online Menüde görebileceği bir mesaj bırakın!\n(Lütfen İngilizce tutun)",
		"Message" => "Mesaj",
		"Open Sidebar" => "Kenar Çubuğunu Aç",
		"Open the Network Sidebar" => "Ağ Kenar Çubuğunu Aç",
		", if you aren't able to.\n(Press " => ", eğer açamıyorsanız.\n(",
		" to open it at any time!)" => " tuşuna basarak istediğiniz zaman açabilirsiniz!)",
		"Login to Browser" => "Tarayıcıya Giriş Yap",
		"Authenticates you to the network in your default web browser" => "Varsayılan web tarayıcınızda ağa kimlik doğrulaması yapar",
		"Change Email Address" => "E-posta Adresini Değiştir",
		"Use the following format:\n<new_mail> from <old_mail>" => "Şu formatı kullanın:\n<yeni_mail> from <eski_mail>",
		"new@example.org from old@example.org" => "yeni@ornek.com from eski@ornek.com",
		"Email Successfully Added!" => "E-posta Başarıyla Eklendi!",
		"Delete Network Account" => "Ağ Hesabını Sil",
		"Bye!" => "Hoşça kal!",
		"Are you sure you want to delete your account?\n(This action is irreversible!)" => "Hesabınızı silmek istediğinizden emin misiniz?\n(Bu işlem geri alınamaz!)",
		"Account Deleted" => "Hesap Silindi",
		"Logout of the Network" => "Ağdan Çıkış Yap",
		"Logout of the Psych Online Network" => "Psych Online Ağından çıkış yap",
		"Are you sure you want to logout?" => "Çıkış yapmak istediğinizden emin misiniz?",
		
		// FindRoomState
		"Looking for a room." => "Oda arıyor.",
		"ACCEPT - Enter selected room." => "KABUL ET - Seçili odaya gir.",
		"No available rooms found!" => "Mevcut oda bulunamadı!",
		"Couldn't connect!" => "Bağlanılamadı!",
		"ERROR: " => "HATA: ",
		"\nTry again in a few minutes! The server is probably restarting!" => "\nBirkaç dakika sonra tekrar deneyin! Sunucu muhtemelen yeniden başlatılıyor!",
		"> Enter: " => "> Giriş: ",
		
		// DownloaderState
		"Browsing mods on GameBanana." => "GameBanana'da modlara göz atıyor.",
		"Search mods here // Enter a URL to download..." => "Modları buradan ara // İndirmek için URL girin...",
		"< Page " => "< Sayfa ",
		" >" => " >",
		" - Go to previous page" => " - Önceki sayfaya git",
		" - Go to next page" => " - Sonraki sayfaya git",
		"Error: " => "Hata: ",
		"Mods not found!" => "Mod bulunamadı!",
		"No mods found!" => "Hiç mod bulunamadı!",
		"Fetching downloads failed!" => "İndirmeler getirilemedi!",
		"That mod is deleted!" => "Bu mod silinmiş!",
		
		// SetupModsState
		"Mods URL Setup" => "Mod URL Kurulumu",
		"Before you play, it is recommended to set links for your mods!\nSelect mods with " => "Oynamadan önce, modlarınız için link ayarlamanız önerilir!\nModları seçmek için ",
		", Leave with " => ", Çıkmak için ",
		"\nHold " => "\nTüm değişiklikleri iptal etmek için çıkarken ",
		" while exiting to discard all changes" => " tuşuna basılı tutun",
		"ACCEPT, Paste links with CTRL + V" => "KABUL ET, CTRL + V ile link yapıştırın",
		"BACK" => "GERİ",
		
		// StoryMenuState
		"Story Mode" => "Hikaye Modu",
		
		// Score Text
		"PlayState.updateTeamSide.daText" => "%{1}%
			\nSkor: %{2}%
			\nIskalar: %{3}%
			\nDoğruluk: %{4}%%" + (ClientPrefs.data.showFP ? '\nFP: %{5}%' : '') + "\nGecikme: %{6}%ms",

		"PlayState.updateScoreSID.if (countSide > 1).daText" => 
			'%{1}%: %{2}% | %{3}% M | %{4}%% - %{5}%' + (ClientPrefs.data.showFP ? ' | %{6}%FP' : '') + ' | %{7}%ms',

		"PlayState.updateScoreSID.else.daText" => '%{1}%\nSkor: %{2}%\nIskalar: %{3}%\nRating: %{4}%' + (ClientPrefs.data.showFP ? '\nFP: %{5}%' : '') + "\nGecikme: %{6}%",
		"PlayState.updateScore.scoreTextObject" => "Skor: %{1}% | Iskalar: %{2}% | Doğruluk: %{3}%",
	];
	
	//normal texts will go there when turkish version done
	public static var normalTexts:Map<String, String> = [
		"FlashingState.warnText" => "Hey, watch out!\n
			This game can trigger photosensitive epilepsy! \n
			If you have motion sickness you should check these settings!  \n\n
			Press %{1}% to check Accessibility Settings.\n
			Press %{2}% to ignore this message.\n\n
			(These settings will not block all effects)\n
			You've been warned!",

		"PlayState.updateTeamSide.daText" => "%{1}%
			\nScore: %{2}%
			\nMisses: %{3}%
			\nAccuracy: %{4}%%" + (ClientPrefs.data.showFP ? '\nFP: %{5}%' : '') + "\nPing: %{6}%ms",

		"PlayState.updateScoreSID.if (countSide > 1).daText" => 
			'%{1}%: %{2}% | %{3}% M | %{4}%% - %{5}%' + (ClientPrefs.data.showFP ? ' | %{6}%FP' : '') + ' | %{7}%ms',

		"PlayState.updateScoreSID.else.daText" => '%{1}%\nScore: %{2}%\nMisses: %{3}%\nRating: %{4}%' + (ClientPrefs.data.showFP ? '\nFP: %{5}%' : '') + "\nPing: %{6}%",
		"PlayState.updateScore.scoreTextObject" => "Score: %{1}% | Misses: %{2}% | Rating: %{3}%"
	];
	
	public static inline function getText(ogText:String, ?args:Array<Dynamic>):String {
		var text:String = ogText;

		if (turkishTexts.exists(text) && ClientPrefs.data.lang == "TR")
			text = turkishTexts.get(text);
		else if (normalTexts.exists(text))
			text = normalTexts.get(text);

		if (args != null && args.length > 0) {
			for (i in 0...args.length) {
				var placeholder:String = "%{" + (i + 1) + "}%";
				args[i] = Std.string(args[i]);
				text = StringTools.replace(text, placeholder, args[i]);
			}
		}

		return text;
	}
}